### ISSUE TITLE
 No plugin found for prefix 'scala'  error

### ISSUE THREAD

**Issue by Nasreddine** [dbpedia/lookup#11]
I'm trying to re-build the index for my own DBpedia lookup service.
I've encountered the following error after execution the indexer : 

Picked up JAVA_TOOL_OPTIONS: -javaagent:/usr/share/java/jayatanaag.jar 
[INFO] Scanning for projects...
Downloading: http://repo.maven.apache.org/maven2/org/codehaus/mojo/maven-metadata.xml
Downloading: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-metadata.xml
Downloaded: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-metadata.xml (13 KB at 15.7 KB/sec)
Downloaded: http://repo.maven.apache.org/maven2/org/codehaus/mojo/maven-metadata.xml (22 KB at 10.6 KB/sec)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.912s
[INFO] Finished at: Sat Jun 28 10:37:59 CET 2014
[INFO] Final Memory: 8M/205M
[INFO] ------------------------------------------------------------------------
[ERROR] No plugin found for prefix 'scala' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (/home/nasreddine/.m2/repository), central (http://repo.maven.apache.org/maven2)] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/NoPluginFoundForPrefixException

**Comment by malcolmgreaves** [comment]
Any success?

**Comment by Nasreddine** [comment]
You can follow this discussion :
https://www.mail-archive.com/dbpedia-discussion@lists.sourceforge.net/msg06532.html

**Comment by sandroacoelho** [comment]
Hi @Nasreddine , @malcolmgreaves 

Index rebuilding is working as well.  Maybe you would like to try this [script] (https://github.com/dbpedia/lookup/blob/master/scripts/index.sh)

Best,
