### ISSUE TITLE
Rebuilding the index

### ISSUE THREAD

**Issue by Cerbal** [dbpedia/lookup#12]
Hello everyone,

I am currently rebuilding the index, in order to have the latest data from dbpedia.

I am stuck at the part:
"pignlproc output from nerd-stats.pig"

 At first, just to know what it is about, what is this file doing? Can the look-up work without this file? 

Then, is the nerd-stats.pig a very intensive script that requires a hadoop cluster of several machines? Or is it ok to run it on a laptop?

Thanks you by advance,
Sam

**Comment by sandroacoelho** [comment]
Hi @Cerbal 

There are two forms to do it. If you don't feel comfortable with Apache Pig, I recommend you use run Indexer with DBpedia data. Maybe you would like to try this automated [script](https://github.com/dbpedia/lookup/blob/master/scripts/index.sh)

Best,
