### ISSUE TITLE
DBpedia lookup service is unavailable

### ISSUE THREAD

**Issue by bpandres** [dbpedia/lookup#14]
Hi, I've been using the lookup service for the last few weeks with no issues but since this weekend I keep getting a Service Temporarily Unavailable message from both the Keyword Search & Autocomplete.

I'm assuming the service is going through some maintenance but just wanted to check just in case you guys weren't aware of the issue.

Thanks in advance!

**Comment by sandroacoelho** [comment]
Hi @bpandres 
The service is up.
