### ISSUE TITLE
Cannot start Server without maven

### ISSUE THREAD

**Issue by ktk** [dbpedia/lookup#15]
I try to figure out how to start the server without maven, as maven is not really useful in a headless server environment with a service management framework for starting/stopping the process.

The current `run` script does not really help as it just triggers maven and I couldn't figure out how to launch it manually.

I tried multiple things, for example:

    java  -Xmx512m -Dlogback.configurationFile=logback.xml -Dhttp.port=1111 -jar target/dbpedia-lookup-3.1.jar  org.dbpedia.lookup.server.Server

But it complains about missing main manifest and does not seem to execute `org.dbpedia.lookup.server.Server`:

    no main manifest attribute, in target/dbpedia-lookup-3.1.jar

**Comment by sandroacoelho** [comment]
Hi @ktk 

This problem was solved in PR #22 .

Now, you can run just typing java -jar dbpedia-lookup-3.1-jar-with-dependencies.jar index_path

Best,

**Comment by ktk** [comment]
thanks @sandroacoelho ! If I get that correctly there is even a docker image now, perfect!
