### ISSUE TITLE
org.dbpedia.lookup.server.Server: do not open a site

### ISSUE THREAD

**Issue by ktk** [dbpedia/lookup#16]
If the server is started via the run script it seems to try to open a URI with an example search query. While this might make sense during testing this is not really useful in production environment as we neither have an X11 server nor a web browser installed so it ends in an error message.

This should be removed from the default server configuration.

**Comment by sandroacoelho** [comment]
:+1: I've removed it in PR #22

**Comment by ktk** [comment]
Great tnx!
