### ISSUE TITLE
Lookup service down for past 24 hours

### ISSUE THREAD

**Issue by abennett1229** [dbpedia/lookup#17]
I have not been getting a response from this web service. I'm getting ERR_CONNECTION_TIMED_OUT.

For your reference:
http://lookup.dbpedia.org/api/search/PrefixSearch?QueryClass=&MaxHits=5&QueryString=berl

**Comment by VincentMolinie** [comment]
Same here =/. What's happening ?

**Comment by sandroacoelho** [comment]
Hi @abennett1229 , @VincentMolinie. 

The service is available again. Sorry for the inconvenience

**Comment by busfahren** [comment]
PrefixSearch is down again (500 Server error).
