### ISSUE TITLE
Unable to execute "./run Server dbpedia-lookup-index-3.8"

### ISSUE THREAD

**Issue by coderabhishek** [dbpedia/lookup#27]
After downloading dbpedia-lookup-index and mvn install "./run Server dbpedia-lookup-index-3.8" doesn't works.It gives following error:

[INFO] --- scala-maven-plugin:3.2.2:testCompile (test-compile) @ dbpedia-lookup ---
[WARNING]  Expected all dependencies to require Scala version: 2.11.7
[WARNING]  org.dbpedia.lookup:dbpedia-lookup:3.1 requires scala version: 2.11.7
[WARNING]  org.scala-lang:scala-compiler:2.11.7 requires scala version: 2.11.7
[WARNING]  org.scala-lang:scala-reflect:2.11.7 requires scala version: 2.11.7
[WARNING]  org.scala-lang.modules:scala-xml_2.11:1.0.4 requires scala version: 2.11.4
[WARNING] Multiple versions of scala libraries detected!
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] <<< scala-maven-plugin:3.2.2:run (default-cli) < test-compile @ dbpedia-lookup <<<
[INFO] 
[INFO] --- scala-maven-plugin:3.2.2:run (default-cli) @ dbpedia-lookup ---
[WARNING]  Expected all dependencies to require Scala version: 2.11.7
[WARNING]  org.dbpedia.lookup:dbpedia-lookup:3.1 requires scala version: 2.11.7
[WARNING]  org.scala-lang:scala-compiler:2.11.7 requires scala version: 2.11.7
[WARNING]  org.scala-lang:scala-reflect:2.11.7 requires scala version: 2.11.7
[WARNING]  org.scala-lang.modules:scala-xml_2.11:1.0.4 requires scala version: 2.11.4
[WARNING] Multiple versions of scala libraries detected!
[INFO] launcher 'Server' selected => org.dbpedia.lookup.server.Server
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at scala_maven_executions.MainHelper.runMain(MainHelper.java:164)
	at scala_maven_executions.MainWithArgsInFile.main(MainWithArgsInFile.java:26)
Caused by: org.apache.lucene.index.IndexNotFoundException: no segments* file found in org.apache.lucene.store.MMapDirectory@/home/abhishek/lookup/dbpedia-lookup-index-3.8 lockFactory=org.apache.lucene.store.NativeFSLockFactory@7a003aca: files: [dbpedia-lookup-index-3.8]
	at org.apache.lucene.index.SegmentInfos$FindSegmentsFile.run(SegmentInfos.java:667)
	at org.apache.lucene.index.DirectoryReader.open(DirectoryReader.java:72)
	at org.apache.lucene.index.IndexReader.open(IndexReader.java:256)
	at org.dbpedia.lookup.lucene.Searcher.<init>(Searcher.scala:21)
	at org.dbpedia.lookup.server.Server$.main(Server.scala:51)
	at org.dbpedia.lookup.server.Server.main(Server.scala)
	... 6 more
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.877 s
[INFO] Finished at: 2016-02-28T17:10:35+05:30
[INFO] Final Memory: 17M/248M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal net.alchim31.maven:scala-maven-plugin:3.2.2:run (default-cli) on project dbpedia-lookup: wrap: org.apache.commons.exec.ExecuteException: Process exited with an error: 240 (Exit value: 240) -> [Help 1]

**Comment by sandroacoelho** [comment]
Hi @coderabhishek, sorry for the delay.

It seems that your index folder doesn't have a segments* file. I've created new indexes for English and are available [here](https://sourceforge.net/projects/dbpedia-lookup/files/index/).

Could you , please, download the [en_current.tar.gz](https://sourceforge.net/projects/dbpedia-lookup/files/index/en_current.tar.gz/), unpack it and run ` ./run Server dbpedia-lookup-index/en/current/core-i18n` ?

**Comment by sandroacoelho** [comment]
Also... Thanks for test the README procedures. I've just upgraded it.

**Comment by coderabhishek** [comment]
Thanks @sandroacoelho ,I'm able to run local mirror and make some test API calls.Is there something else I can do to get a good understanding of code base?

**Comment by sandroacoelho** [comment]
Hi @coderabhishek :

You can start basically doing three things:

* Debug the code using an IDE such as Intellij, Eclipse etc - It will help you feel comfortable with the codebase;

*Look inside the Lookup index (It is a Lucene index).  You can use [Luke] (http://www.getopt.org/luke/) for it .  - It's really important to know how the information is organized;

And finally

* Explore the API through using browser/curl combining parameters.
E.g 
 `curl http://localhost:1111/api/search/KeywordSearch?QueryClass=place&QueryString=berlin ` 


Best,
