### ISSUE TITLE
Local mirror: Refcount always 0

### ISSUE THREAD

**Issue by HugoSousa** [dbpedia/lookup#28]
I successfully mirrorred the web service locally. However, the `Refcount `is always 0, so the results are not properly sorted, as in the hosted version. 

EDIT: I realized now that the field `description` is also always coming `null`.

I downloaded the index from the [link in README](https://sourceforge.net/projects/dbpedia-lookup/files/index/) and I'm executing the following command:
`mvn scala:run "-Dlauncher=Server" "-DaddArgs=dbpedia-lookup-index/en/2015-04/core-i18n"` 

Do the previously built indexes contain the redirects included? Or am I missing something?

**Comment by sandroacoelho** [comment]
Hi @HugoSousa,

I will check this issue asap.

Best,

**Comment by MikeLx** [comment]
Is the dbpedia lookup service coming back? It's been down for 3 days now.

**Comment by sandroacoelho** [comment]
Hi @MikeLx  ,
The service is up again.

**Comment by sandroacoelho** [comment]
Hi @HugoSousa 

So sorry for the big delay. We finally have an index with refcounts (Hope it is useful). It is available [here](https://www.dropbox.com/sh/x338n4le2svy2jb/AAAY8_DTZj-Y7Mku29oVhiDla?dl=0). 

I also updated our README with how to build a new index with this info. Thanks @jodaiber for the explanation.
