### ISSUE TITLE
The online dbpedia lookup service is down.

### ISSUE THREAD

**Issue by fellahst** [dbpedia/lookup#29]
We are using the DBPedia Lookup online web service  and it seems to be down today. 

http://lookup.dbpedia.org/api/search.asmx/KeywordSearch?QueryClass=place&QueryString=berlin

I would appreciate if the maintainers of the service could have a look at it and put it back online. Thanks !

**Comment by sandroacoelho** [comment]
Hi @fellahst ,

The service is up again.

Best,

**Comment by datawlb** [comment]
Can I ask how to use the "http get" get the array results of the online api, I don't know how to parse it as a   
standard format. Thank you very much!
