### ISSUE TITLE
different results in public API and in local server

### ISSUE THREAD

**Issue by vefthym** [dbpedia/lookup#36]
Hi, when I execute the query: 
> http://localhost:1111/api/search/KeywordSearch?QueryClass=&QueryString=berlin

in my localhost, I get different results than those on the public server, as shown below (only the URIs of the results are shown here for easier reading). 
Is it an issue of different versions? Which one is running on the public server?

      <URI>http://dbpedia.org/resource/Dada</URI>
      <URI>http://dbpedia.org/resource/Central_European_Time</URI>
      <URI>http://dbpedia.org/resource/Kingdom_of_Prussia</URI>
      <URI>http://dbpedia.org/resource/Golden_Bear</URI>
      <URI>http://dbpedia.org/resource/Spandau</URI>

**Comment by sandroacoelho** [comment]
Hi @jimkont . Could you give a hand here?

Thanks

**Comment by boyarintsev** [comment]
I've got the same issue. First thought I cannot pass the correct index, but after some testing it looks good. Could it be the problem with the index bundle 2015-04 itself? Will appreciate any help a lot!

**Comment by boyarintsev** [comment]
Hi @vefthym !
May I ask you, have you found a solution?

**Comment by sandroacoelho** [comment]
Hi @boyarintsev ,

Maybe can be a problem with 2015-04. I can rebuild it and make available 2015-10 and 2016-04. 
Could you, please, provide us more examples of the problems that you are facing?

**Comment by boyarintsev** [comment]
Hi @sandroacoelho !

I'm just getting different sets of results from the demo and from the local instance. Or maybe I'm missing something.
![demo](https://cloud.githubusercontent.com/assets/4397413/18676738/57d382cc-7f5f-11e6-973c-465fefa65bb3.png)
![local](https://cloud.githubusercontent.com/assets/4397413/18676745/5e0a82d0-7f5f-11e6-99d6-a852b38285a8.png)

**Comment by sandroacoelho** [comment]
Hi @boyarintsev . It's a bug in our index. I will check it ASAP.

**Comment by boyarintsev** [comment]
Thanks a lot, Sandro!

**Comment by sandroacoelho** [comment]
Hi @boyarintsev , @vefthym 

It's done. Please try

```
docker run -p 1111:1111 -it dbpedia/lookup java -jar /opt/lookup/dbpedia-lookup-3.1-jar-with-dependencies.jar /opt/lookup/2015-10/
```

I forgot to include instance files (instance_types_en.ttl, instance_types_sdtyped_dbo_en.ttl, instance_types_transitive_en.ttl)  into the index. I've updated our README with these new instructions.


Best,

**Comment by boyarintsev** [comment]
Hi @sandroacoelho ,
It works! Thanks a lot.

I will appreciate a lot if you could answer one more question. Is there a way to obtain some measure of how the system is sure in the result provided. For instance, us -> United States of America (95%)

Thanks,
Alex

**Comment by vefthym** [comment]
Hi @sandroacoelho and @boyarintsev, 

thanks for taking care of that. I do not have time at this point to check it, but since both of you reproduced the same issue as me and it now works for both, I believe you can close the issue. 

Thanks for fixing that!
Vasilis

**Comment by sandroacoelho** [comment]
Hi @boyarintsev ,

Great to hear that is working now. 

>> will appreciate a lot if you could answer one more question. Is there a way to obtain some measure of how the system is sure in the result provided. For instance, us -> United States of America (95%)

Yes, It's possible. Let's open a new issue to talk about it

**Comment by sandroacoelho** [comment]
Hi @boyarintsev ,

I have opened a new issue #43. 

I have a vague idea on how to do it. I will share there  and then we can discuss.

Best,
