### ISSUE TITLE
public PrefixQuery/lookup not working

### ISSUE THREAD

**Issue by jblom** [dbpedia/lookup#37]
Since a couple of days the public end-point is not working anymore: 

http://lookup.dbpedia.org/api/search/PrefixSearch?QueryClass=&MaxHits=5&QueryString=berl

returns a blank page

For now I am not interested in running & maintaining a local instance (in the prototype phase of a project)

**Comment by victoyip** [comment]
Seeing the same issue today.

**Comment by cemilabis** [comment]
Keyword search is working but prefix search is returning Http 500.

**Comment by AlexClibbon** [comment]
![image](https://cloud.githubusercontent.com/assets/16541248/17695808/2afdc18c-63a2-11e6-8f8d-ebbcac161685.png)
Reporting the same thing here - internal server error.

**Comment by davidspringer** [comment]
I am seeing the same error.

**Comment by jimkont** [comment]
We reported the downtime to the lookup service maintainers and waiting  for their actions
sorry for any inconvenience this may caused...

Please note that we also provide a docker image of the service for local deployments
https://hub.docker.com/r/dbpedia/lookup/

**Comment by victoyip** [comment]
Looks like it is working now
