### ISSUE TITLE
Error message when updating to 3.8

### ISSUE THREAD

**Issue by HeikoPaulheim** [dbpedia/lookup#5]
Failed to execute goal on project dbpedia-lookup: Could not resolve dependencies for project org.dbpedia.lookup:dbpedia-lookup:war:3.1: Could not find artifact org.dbpedia.extraction:core:jar:3.8 in nxparser-repo (http://nxparser.googlecode.com/svn/repository)

**Comment by sandroacoelho** [comment]
Hi @HeikoPaulheim. 

 My apologies for that. DBpedia lookup depends of DBpedia Extraction Framework. We have recently deployed this on Maven Central and now it works without clone / compile extraction locally.  

If you have some trouble related, could you please open a new issue?
