### ISSUE TITLE
PrefixSearch broken ?

### ISSUE THREAD

**Issue by fellahst** [dbpedia/lookup#50]
The following query gives a 500 error. 
http://lookup.dbpedia.org/api/search/PrefixSearch?MaxHits=5&QueryString=banana

Keyword search seems to work.

**Comment by sandroacoelho** [comment]
Hi @fellahst ,

Please try http://lookup.dbpedia-spotlight.org/api/search/PrefixSearch?MaxHits=5&QueryString=banana instead. 

Best!

**Comment by sandroacoelho** [comment]
Fixed!
