### ISSUE TITLE
Maintained Question

### ISSUE THREAD

**Issue by TheDeployGuy** [dbpedia/lookup#53]
Hey guys,

I am using this service and loves the ability it gives my application but it seems like PrefixSearch is down and has been last 7 days, I was wondering who maintains that on the actual dbpedia servers? Is it actively maintained?

Thanks and sorry if it has been asked before

Jason

**Comment by sandroacoelho** [comment]
Hi @TheDeployGuy 

Lookup can be downloaded from http://downloads.dbpedia-spotlight.org/dbpedia_lookup/. lookup.dbpedia.org uses 2015-04.tar.gz model.

I am going install it under lookup.dbpedia-spotlight.org today and ask @mgns to move the DNS to this new address.

We are working on a new version. Stay tuned!

Best,

**Comment by TheDeployGuy** [comment]
thanks a lot!
