### ISSUE TITLE
Lookup prefix search results with 500 internal server error

### ISSUE THREAD

**Issue by cuneytyvz** [dbpedia/lookup#54]
http://lookup.dbpedia.org/api/search/PrefixSearch?QueryString=test results with 500 internal server error since at least two weeks. Are there any alternatives we can use for prefix search or will this error be fixed?

**Comment by TheDeployGuy** [comment]
@sandroacoelho Sorry for tagging you, just wondering if there is a better way to reach out to the dbpedia guys to report issues?

**Comment by sandroacoelho** [comment]
Hi @cuneytyvz , @TheDeployGuy 

Lookup can be downloaded from http://downloads.dbpedia-spotlight.org/dbpedia_lookup/. lookup.dbpedia.org uses 2015-04.tar.gz model.

I am going install it under lookup.dbpedia-spotlight.org today and ask @mgns to move the DNS to this new address.

Best,

**Comment by sandroacoelho** [comment]
Hi @cuneytyvz , @TheDeployGuy,

http://lookup.dbpedia-spotlight.org/api/search/PrefixSearch?QueryString=Berlinale works!

Best,

**Comment by sandroacoelho** [comment]
Fixed at http://lookup.dbpedia.org
