### ISSUE TITLE
The online dbpedia lookup service is down

### ISSUE THREAD

**Issue by PeterRakke** [dbpedia/lookup#62]
Hi there,

We are using the DBPedia Lookup online web service and it seems to be down:
[http://lookup.dbpedia.org/api/search.asmx/KeywordSearch?QueryClass=place&QueryString=Amsterdam](http://lookup.dbpedia.org/api/search.asmx/KeywordSearch?QueryClass=place&QueryString=Amsterdam)

I would appreciate if you could take look and get it back online.

Thanks!

**Comment by holycrab13** [comment]
Hi,
Sorry for the inconvenience, the API endpoints have changed to:
https://lookup.dbpedia.org/api/search?typeName=place&query=Amsterdam
and
https://lookup.dbpedia.org/api/prefix?typeName=place&query=Amsterdam

I will add a redirect for the old API as well
This repository will be closed soon, please refer to the new repo (the DBpedia Lookup software has been rebuilt)
https://github.com/dbpedia/dbpedia-lookup

**Comment by PeterRakke** [comment]
Thx!
