### ISSUE TITLE
Returned result isn't precise 

### ISSUE THREAD

**Issue by Nasreddine** [dbpedia/lookup#7]
I tried to get resources correspond to "Programmer", I got :
http://dbpedia.org/resource/B_movie
http://dbpedia.org/resource/Computer_programming
...

http://dbpedia.org/resource/Programmer exists in DBpedia, but wasn't returned.

Any explanation, please ?

**Comment by sandroacoelho** [comment]
Hi @Nasreddine,

Lookup service recovery the most relevant resources for your query based on links in Wikipedia. You can increase the range using &MaxHits= parameter. The default is 5. The resource that you are looking for is in top 10. Please [try it] (http://lookup.dbpedia.org/api/search/PrefixSearch?QueryString=Programmer&MaxHits=10)

Best,
