### ISSUE TITLE
Empty Result Set

### ISSUE THREAD

**Issue by mtsofteng** [dbpedia/lookup#9]
I am using the code for the lookup-service but it seems that it returns an empty result set even for cases it should return results e.g. http://lookup.dbpedia.org/api/search.asmx/KeywordSearch?QueryString=photography
I noticed that in the line sax.parse(ins,this) keeps giving me zero.
Nevertheless, I am not sure how I should use the methods startelement(), endlement() etc. Could you please help me to figure tout what is happening and how should I use the abovementioned methods?

Thank you in advance.

**Comment by sandroacoelho** [comment]
Hi @mtsofteng 

Seems that bug doesn't exists anymore.   I am closing your issue.

Best,
